# Generated by Django 2.2.2 on 2019-07-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BordroNo', models.CharField(max_length=10)),
                ('BordroTarihi', models.DateField()),
                ('CekNo', models.CharField(max_length=10)),
                ('Tipi', models.CharField(max_length=1)),
                ('Durum', models.CharField(max_length=1)),
                ('Vade', models.DateField()),
                ('Tutar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Doviz', models.CharField(max_length=10)),
                ('CariKodu', models.CharField(max_length=10)),
                ('BankaAdi', models.CharField(max_length=50)),
                ('SubeKodu', models.CharField(max_length=50)),
                ('HesapNo', models.IntegerField()),
                ('OdemeYeri', models.CharField(max_length=100)),
                ('IsSaved', models.BooleanField(default=False)),
                ('IsVerified', models.BooleanField(default=False)),
                ('IsDeleted', models.BooleanField(default=False)),
                ('IsCanceled', models.BooleanField(default=False)),
                ('IsTransferred', models.BooleanField(default=False)),
                ('IsTransferCache', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OdemeAraciNoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BordroNo', models.CharField(max_length=10, null=True)),
                ('CekNo', models.CharField(max_length=10, null=True)),
                ('SenetNo', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Senet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BordroNo', models.CharField(max_length=10)),
                ('BordroTarihi', models.DateField()),
                ('SenetNo', models.CharField(max_length=10)),
                ('Tipi', models.CharField(max_length=1)),
                ('Durum', models.CharField(max_length=1)),
                ('Vade', models.DateField()),
                ('Tutar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Doviz', models.CharField(max_length=10)),
                ('CariKodu', models.CharField(max_length=10)),
                ('OdemeYeri', models.CharField(max_length=50)),
                ('IsSaved', models.BooleanField(default=False)),
                ('IsVerified', models.BooleanField(default=False)),
                ('IsDeleted', models.BooleanField(default=False)),
                ('IsCanceled', models.BooleanField(default=False)),
                ('IsTransferred', models.BooleanField(default=False)),
                ('IsTransferCache', models.BooleanField(default=False)),
            ],
        ),
    ]
