# Generated by Django 2.2.2 on 2019-07-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stok',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StokKodu', models.CharField(max_length=10)),
                ('StokAdi', models.CharField(max_length=100)),
                ('StokNitelik', models.CharField(max_length=10)),
                ('StokMiktar', models.IntegerField()),
                ('AlisFiyati', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('SatisFiyati', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('KdvOrani', models.IntegerField()),
                ('StokKaydiOlusturan', models.CharField(max_length=50)),
                ('StokKayitTarihi', models.DateTimeField()),
                ('StokKaydiDuzenleyen', models.CharField(max_length=50, null=True)),
                ('StokDuzenlemeTarihi', models.DateTimeField(null=True)),
                ('IsSaved', models.BooleanField(default=False)),
                ('IsVerified', models.BooleanField(default=False)),
                ('IsDeleted', models.BooleanField(default=False)),
                ('IsCanceled', models.BooleanField(default=False)),
                ('IsTransferred', models.BooleanField(default=False)),
                ('IsTransferCache', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StokHareketleri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StokKodu', models.CharField(max_length=10)),
                ('StokAdi', models.CharField(max_length=100)),
                ('StokNitelik', models.CharField(max_length=10)),
                ('StokMiktar', models.IntegerField()),
                ('AlisFiyati', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('SatisFiyati', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('SonIskontoOrani', models.IntegerField(blank=True, null=True)),
                ('StokHareketiOlusturan', models.CharField(max_length=50)),
                ('StokHareketTarihi', models.DateTimeField()),
                ('IsSaved', models.BooleanField(default=False)),
                ('IsVerified', models.BooleanField(default=False)),
                ('IsDeleted', models.BooleanField(default=False)),
                ('IsCanceled', models.BooleanField(default=False)),
                ('IsTransferred', models.BooleanField(default=False)),
                ('IsTransferCache', models.BooleanField(default=False)),
            ],
        ),
    ]
