# Generated by Django 2.2.2 on 2019-07-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Irsaliye',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IrsaliyeNo', models.CharField(max_length=10)),
                ('IrsaliyeTipi', models.CharField(max_length=10)),
                ('DuzenlenmeTarihi', models.DateField()),
                ('DuzenlenmeSaati', models.TimeField()),
                ('SevkTarihi', models.DateField()),
                ('SevkSaati', models.TimeField()),
                ('TeslimEden', models.CharField(max_length=30)),
                ('TeslimAlan', models.CharField(max_length=30)),
                ('TeslimSaati', models.TimeField()),
                ('CariKodu', models.CharField(max_length=10)),
                ('KullaniciKodu', models.CharField(max_length=10)),
                ('ToplamBrutTutar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ToplamKdv', models.DecimalField(decimal_places=2, max_digits=10)),
                ('IsSaved', models.BooleanField(default=False)),
                ('IsVerified', models.BooleanField(default=False)),
                ('IsDeleted', models.BooleanField(default=False)),
                ('IsCanceled', models.BooleanField(default=False)),
                ('IsTransferred', models.BooleanField(default=False)),
                ('IsTransferCache', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='IrsaliyeHareketleri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IrsaliyeNo', models.CharField(max_length=10)),
                ('IrsaliyeTipi', models.CharField(max_length=10)),
                ('SevkTarihi', models.DateField()),
                ('StokKodu', models.CharField(max_length=10)),
                ('Miktar', models.IntegerField()),
                ('Nitelik', models.CharField(max_length=10)),
                ('BirimFiyat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('IskontoOrani', models.IntegerField(blank=True, default=0, null=True)),
                ('KdvOrani', models.IntegerField()),
                ('IsSaved', models.BooleanField(default=False)),
                ('IsVerified', models.BooleanField(default=False)),
                ('IsDeleted', models.BooleanField(default=False)),
                ('IsCanceled', models.BooleanField(default=False)),
                ('IsTransferred', models.BooleanField(default=False)),
                ('IsTransferCache', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='IrsaliyeNo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SatisIrsaliyesiNo', models.CharField(max_length=10)),
            ],
        ),
    ]
